task: S2T
device: cuda
do_translation: True
do_recognition: True
data:
  train_label_path: /home/user/work/Preprocessing/MSKA/Dataset/data/Phoenix-2014T.train.pkl
  dev_label_path: /home/user/work/Preprocessing/MSKA/Dataset/data/Phoenix-2014T.dev.pkl
  test_label_path: /home/user/work/Preprocessing/MSKA/Dataset/data/Phoenix-2014T.test.pkl
  max_length: 300
  input_streams: keypoint
  level: word
  max_sent_length: 400
  dataset_name: Phoenix-2014T
  augmentation: # Para desactivar poner a 0
    joint_dropout: 0
    gaussian_noise: 0
  text_max_length: 128

testing:
  recognition:
    beam_size: 5
  translation:
    max_new_tokens: 51
    num_beams: 4               # 4 o 5 está bien
    length_penalty: 0.5       # No forzar frases extremadamente largas
    repetition_penalty: 1.5    # Castiga fuertemente repetir tokens
    no_repeat_ngram_size: 3    #  Prohíbe repetir bloques de 3 palabras seguidas
    early_stopping: true       # Obliga al Beam Search a detenerse en cuanto encuentra un <eos>
    temperature: 0.05
    do_sample: false

gloss:
  gloss2id_file: data/gloss2ids.pkl
training:
  wandb: online # online or disabled
  model_dir: /home/user/work/data/outputs_final/SLT_SLM_ALL
  validation:
    recognition:
      beam_size: 1
    translation:
      max_new_tokens: 51
      num_beams: 4
      length_penalty: 0.5
      repetition_penalty: 1.5
      no_repeat_ngram_size: 3
      early_stopping: true
      temperature: 0.05
      do_sample: false
  optimization:
    optimizer: AdamW
    learning_rate:
      default: 1.0e-05
      mapper: 2.0e-5        # VLMapper: ahora preentrenado
      lora: 2.0e-4          # LoRA: sobre preentrenado
      gloss_embedding: 2.0e-5  # tabla de embeddings de glosas
      recognition: 1.0e-06  # recognition: prácticamente congelado
    weight_decay: 0.02
    betas:
      - 0.9
      - 0.998
    scheduler: cosineannealing
    t_max: 40

model:
  RecognitionNetwork:
    ensemble_method: uniform
    pretrained_path: /home/user/work/data/outputs_final/SLR_base/best_checkpoint.pth
    input_type: keypoint
    DSTA-Net:
      net: [[64, 64, 16, 7, 2], [64, 64, 16, 3, 1],
            [64, 128, 32, 3, 1], [128, 128, 32, 3, 1],
            [128, 256, 64, 3, 2], [256, 256, 64, 3, 1],
            [256, 256, 64, 3, 1], [256, 256, 64, 3, 1],]
      body: [0,1,2,3,4,5,6,7,8,9,10,
               94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,
               115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,
               26,29,32,36,39,42,44,46,49,51,56,59,62,65,68,71,74,75,76,77,78,79,80,82,83,84]

      left:  [0,1,3,5,7,9,
                94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114]

      right: [0,2,4,6,8,10,
                115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135]

      face:  [26,29,32,36,39,42,44,46,49,51,56,59,62,65,68,71,74,75,76,77,78,79,80,82,83,84]
      mouth: [74,75,76,77,78,79,80,82,83,84]
    GlossTokenizer:
      gloss2id_file: data/gloss2ids.pkl
    body_visual_head:
      input_size: 256
      hidden_size: 512
      ff_size: 2048
      pe: True
      ff_kernelsize:
        - 3
        - 3
    fuse_visual_head:
      input_size: 1024
      hidden_size: 512
      ff_size: 2048
      pe: True
      ff_kernelsize:
        - 3
        - 3
    left_visual_head:
      input_size: 512
      hidden_size: 512
      ff_size: 2048
      pe: True
      ff_kernelsize:
        - 3
        - 3
    right_visual_head:
      input_size: 512
      hidden_size: 512
      ff_size: 2048
      pe: True
      ff_kernelsize:
        - 3
        - 3
  TranslationNetwork:
    pretrained_model_name_or_path: "Qwen/Qwen2.5-1.5B"

    # Flags de ablation
    use_visual_features: true
    use_gloss_tokens: false       # cambiar a true para experimento con glosas
    gloss_source: predicted    # 'ground_truth' o 'predicted'

    # LoRA
    lora:
      r: 64
      alpha: 128
      dropout: 0.25
      target_modules: [q_proj, k_proj, v_proj, o_proj]


    # Solo necesario si use_gloss_tokens: true
    GlossTokenizer:
      gloss2id_file: data/gloss2ids.pkl
      src_lang: de_DGS

    GlossEmbedding:
      from_scratch: true
      freeze: false
      gloss2embed_file: data/gloss_embeddings.bin

  VLMapper:
      type: projection
      # in_features se infiere automáticamente de fuse_visual_head.hidden_size (512)
      # out_features se infiere de translation_network.input_dim (hidden_size de Qwen)
      pretrained_mapper: /home/user/work/data/outputs_final/SLT_SLM_ALL/pretrained_mapper.pth
